# Trigger on push to master (+ allow manual runs of this workflow)
# First job: identical steps to PR workflow
# Second job: Deploy to Heroku

name: on-merge-workflow

on:
  # [to be filled]
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        # [rest to be filled]
        run: npm i
      - name: Run tests
        run: npm test

  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # [rest to be filled]
      - name: Build
        uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:push -a web
      - name: Deploy
        run: heroku container:release web
