# Trigger on push to master (+ allow manual runs of this workflow)
# First job: identical steps to PR workflow
# Second job: Deploy to Heroku

name: on-merge-workflow

on:
  # [to be filled]
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        # [rest to be filled]
        run: npm i
      - name: Run tests
        run: npm test

  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # [rest to be filled]
      - name: Build
        uses: actions/checkout@v2
      - name: sign into Container Registry
        run: heroku container:login
      - name: push to Container Registry
        run: heroku container:push web
      - name: Deploy the changes
        run: heroku container:release web
