# Trigger on pull request to master (+ allow manual runs of this workflow)
# Checkout repo, install Node.js, run test

name: pr-workflow

on:
  # [to be filled]
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  test:
    runs-on: # [to be filled]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        # [rest to be filled]
      - name: Run tests
        uses: actions/checkout@v2
        run: npm test
